### ISSUE TITLE
magento raised exception when i view the sales order grid

### ISSUE THREAD

**Issue by kmcheong** [KingIsulgard/Magento-Noble-Extended-Order-Grid#3]
[magento log.txt](https://github.com/KingIsulgard/Magento-Noble-Extended-Order-Grid/files/964019/magento.log.txt)
![custom sales grid](https://cloud.githubusercontent.com/assets/20103132/25524384/f152ce14-2c3c-11e7-838c-7c561b5dc69e.jpg)

Hi,
We get an exception when we enable the sales order grid with the configurable attached in the jpg, and i've also attached magento report so you could see the call stack and error when the exception is raised

**Comment by kmcheong** [comment]
The error goes away when i disable the sku column

**Comment by KingIsulgard** [comment]
Hi kmcheong,

The print screen you sent does not look like the configuration view of the original module. I developed. 
Anyway, there seems to be an error on the SKU column, a column I did not include in my version since such a column does not exist for an order.

**Comment by kmcheong** [comment]
My mistake, I’m sorry, how can I close the issue?

**Comment by KingIsulgard** [comment]
No problem, I'm glad the module is being used ;).
